trunfo/config/routes.rb
Rails.application.routes.draw do
  resources :players
  resources :deck_cards
  resources :decks
  resources :cards
  devise_for :admins
  devise_for :users
  resources :games

  namespace :backoffice do
  get 'dashboard/index'
  end

  get 'site/home/index'
  root 'site/home#index'
  
  mount ActionCable.server => '/cable'

end

trunfo/app/models/player.rb
class Player < ActiveRecord::Base
  belongs_to :user
  belongs_to :game
  has_one :deck
  has_many :deck_cards, through: :deck#, dependent: :destroy #nop
  has_many :cards, through: :deck_cards# , dependent: :destroy #nop
  
    accepts_nested_attributes_for :deck, reject_if: :all_blank, allow_destroy: true
    accepts_nested_attributes_for :deck_cards, reject_if: :all_blank, allow_destroy: true
 #   accepts_nested_attributes_for :cards, reject_if: :all_blank, allow_destroy: true
 

end

trunfo/app/controllers/players_controller.rb
class PlayersController < ApplicationController
  before_action :set_player, only: [:show, :edit, :update, :destroy]

  # GET /players
  # GET /players.json
  def index
    @players = Player.all
  end

  # GET /players/1
  # GET /players/1.json
  def show
  end

  # GET /players/new
  def new
    @player = Player.new
  end

  # GET /players/1/edit
  def edit
  end

  # POST /players
  # POST /players.json
  def create
    @user = current_user
    @player = Player.new(player_params)
    @game = @player.game
    @deck = Deck.create(player:@player, game:@game)
  
    respond_to do |format|
      if @player.save
        format.html { redirect_to @player, notice: 'Player was successfully created.' }
        format.json { render :show, status: :created, location: @player }
      else
        format.html { render :new }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /players/1
  # PATCH/PUT /players/1.json
  def update
    respond_to do |format|
      if @player.update(player_params)
        format.html { redirect_to @player, notice: 'Player was successfully updated.' }
        format.json { render :show, status: :ok, location: @player }
      else
        format.html { render :edit }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /players/1
  # DELETE /players/1.json
  def destroy
    @deck.destroy
    @player.destroy
    respond_to do |format|
      format.html { redirect_to players_url, notice: 'Player was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_player
      @player = Player.find(params[:id])
      @game = Game.find(@player.game_id)
      @deck = Deck.find_by({player:@player})
      @user = current_user
      #raise "There: #{@game}"
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def player_params
      params.require(:player).permit(:user_id, :name, :game_id)
    end
end

trunfo/app/helpers/players_helper.rb
module PlayersHelper
end

trunfo/app/views/players/_form.html.erb
<%= form_for(@player) do |f| %>
  <% if @player.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@player.errors.count, "error") %> prohibited this player from being saved:</h2>

      <ul>
      <% @player.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%#= f.label :user_id %>
    <%#= f.text_field :user_id %>
    <%= f.hidden_field :user_id, :value => current_user.id %>
  <%#= user.id %>

  </div>
    <div class="field">
  <%= f.hidden_field :game_id, :value => @game.id %>
  <%#= game.description %>
</div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

trunfo/app/views/players/edit.html.erb
<h1>Editing Player</h1>

<%= render 'form' %>

<%= link_to 'Show', @player %> |
<%= link_to 'Back', players_path %>

trunfo/app/views/players/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Players</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Name</th>
      <th>Game</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @players.each do |player| %>
      <tr>
        <td><%= player.user %></td>
        <td><%= player.name %></td>
        <td><%= player.game %></td>
        <td><%= link_to 'Show', player %></td>
        <td><%= link_to 'Edit', edit_player_path(player) %></td>
        <td><%= link_to 'Destroy', player, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Player', new_player_path %>

trunfo/app/views/players/new.html.erb
<h1>New Player</h1>

<%= render 'form' %>

<%= link_to 'Back', players_path %>

trunfo/app/views/players/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @player.user %>
</p>

<p>
  <strong>Name:</strong>
  <%= @player.name %>
</p>

<p>
  <strong>Game:</strong>
  <%= @player.game %>
</p>

<%= link_to 'Edit', edit_player_path(@player) %> |
<%= link_to 'Back', players_path %>