trunfo/config/routes.rb
Rails.application.routes.draw do
  resources :players
  resources :deck_cards
  resources :decks
  resources :cards
  devise_for :admins
  devise_for :users
  resources :games

  namespace :backoffice do
  get 'dashboard/index'
  end

  get 'site/home/index'
  root 'site/home#index'
  
  mount ActionCable.server => '/cable'

end

trunfo/app/models/deck_card.rb
class DeckCard < ActiveRecord::Base
  belongs_to :deck#, dependent: :destroy # deck belongs_to player
  belongs_to :card#, dependent: :destroy
  
  validates_uniqueness_of :card, scope: :deck



end

trunfo/app/controllers/deck_cards_controller.rb
class DeckCardsController < ApplicationController
  before_action :set_deck_card, only: [:show, :edit, :update, :destroy]

  # GET /deck_cards
  # GET /deck_cards.json
  def index
    @deck_cards = DeckCard.all
  end

  # GET /deck_cards/1
  # GET /deck_cards/1.json
  def show
  end

  # GET /deck_cards/new
  def new
    @deck_card = DeckCard.new
  end

  # GET /deck_cards/1/edit
  def edit
  end

  # POST /deck_cards
  # POST /deck_cards.json
  def create
    @deck_card = DeckCard.new(deck_card_params)

    respond_to do |format|
      if @deck_card.save
        format.html { redirect_to @deck_card, notice: 'Deck card was successfully created.' }
        format.json { render :show, status: :created, location: @deck_card }
      else
        format.html { render :new }
        format.json { render json: @deck_card.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /deck_cards/1
  # PATCH/PUT /deck_cards/1.json
  def update
    respond_to do |format|
      if @deck_card.update(deck_card_params)
        format.html { redirect_to @deck_card, notice: 'Deck card was successfully updated.' }
        format.json { render :show, status: :ok, location: @deck_card }
      else
        format.html { render :edit }
        format.json { render json: @deck_card.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /deck_cards/1
  # DELETE /deck_cards/1.json
  def destroy
    @deck_card.destroy
    respond_to do |format|
      format.html { redirect_to deck_cards_url, notice: 'Deck card was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_deck_card
      @deck_card = DeckCard.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def deck_card_params
      params.require(:deck_card).permit(:deck_id, :card_id)
    end
end

trunfo/app/helpers/deck_cards_helper.rb
module DeckCardsHelper
end

trunfo/app/views/deck_cards/_deck_card.html.erb
<%# @deck_cards.map do |deckcard| %>
  <%= deck_card.deck.game.description %> - <%= deck_card.deck.player.name %> x <%= deck_card.card.name %><br>
  <%# end %>

trunfo/app/views/deck_cards/_form.html.erb
<%= form_for(@deck_card) do |f| %>
  <% if @deck_card.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@deck_card.errors.count, "error") %> prohibited this deck_card from being saved:</h2>

      <ul>
      <% @deck_card.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :deck_id %><br>
     <%= f.collection_select :deck_id, Deck.where(game:@deck_card.deck.game.id), :id, :player %>
  </div>
  <div class="field">
    <%= f.label :card_id %><br>
    <%= f.text_field :card_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

trunfo/app/views/deck_cards/edit.html.erb
<h1>Editing Deck Card</h1>

<%= render 'form' %>

<%= link_to 'Show', @deck_card %> |
<%= link_to 'Back', deck_cards_path %>

trunfo/app/views/deck_cards/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Deck Cards</h1>

<table>
  <thead>
    <tr>
      <th>Game</th>
      <th>Player</th>
      <th>Card</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @deck_cards.each do |deck_card| %>
      <tr>
        <td><%= deck_card.deck.game.description %></td>
        <td><%= deck_card.deck.player.name %></td>
        <td><%= deck_card.card.name %></td>
        <td><%= link_to 'Show', deck_card %></td>
        <td><%= link_to 'Edit', edit_deck_card_path(deck_card) %></td>
        <td><%= link_to 'Destroy', deck_card, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Deck card', new_deck_card_path %>

trunfo/app/views/deck_cards/new.html.erb
<h1>New Deck Card</h1>

<%= render 'form' %>

<%= link_to 'Back', deck_cards_path %>

trunfo/app/views/deck_cards/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Deck:</strong>
  <%= @deck_card.deck %> belongs to <%= @deck_card.deck.player %>
</p>

<p>
  <strong>Card:</strong>
  <%= @deck_card.card %>
</p>

<%= link_to 'Edit', edit_deck_card_path(@deck_card) %> |
<%= link_to 'Back', deck_cards_path %>