trunfo/config/routes.rb
Rails.application.routes.draw do
  resources :players
  resources :deck_cards
  resources :decks
  resources :cards
  devise_for :admins
  devise_for :users
  resources :games

  namespace :backoffice do
  get 'dashboard/index'
  end

  get 'site/home/index'
  root 'site/home#index'
  
  mount ActionCable.server => '/cable'

end

trunfo/app/models/card.rb
class Card < ActiveRecord::Base
  #  belongs_to :deck_cards, dependent: :destroy
    validates_uniqueness_of :name
      include OrderQuery
  order_query :order_display, [
    [:updated_at, :desc],
    [:id, :desc]
  ]
end

trunfo/app/controllers/cards_controller.rb
class CardsController < ApplicationController
  layout 'cards' #??
  before_action :set_card, only: [:show, :edit, :update, :destroy]

  # GET /cards
  # GET /cards.json
  def index
    @cards = Card.all

    #raise 'error'
  end

  # GET /cards/1
  # GET /cards/1.json
  def show
  end

  # GET /cards/new
  def new
    @card = Card.new
  end

  # GET /cards/1/edit
  def edit
  end

  # POST /cards
  # POST /cards.json
  def create
    @card = Card.new(card_params)

    respond_to do |format|
      if @card.save
        format.html { redirect_to @card, notice: 'Card was successfully created.' }
        format.json { render :show, status: :created, location: @card }
      else
        format.html { render :new }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cards/1
  # PATCH/PUT /cards/1.json
  def update
    respond_to do |format|
      if @card.update(card_params)
        format.html { redirect_to @card, notice: 'Card was successfully updated.' }
        format.json { render :show, status: :ok, location: @card }
      else
        format.html { render :edit }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cards/1
  # DELETE /cards/1.json
  def destroy
    @card.destroy
    respond_to do |format|
      format.html { redirect_to cards_url, notice: 'Card was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_card
      @card = Card.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def card_params
      params.require(:card).permit(:name, :description, :height, :birth, :jump, :trunfo, :imune)
    end
end

trunfo/app/helpers/cards_helper.rb
module CardsHelper
end

trunfo/app/views/cards/_card.html.erb
<% div_id = "card_id_#{@card.id}" -%>
<div id="<%= div_id -%> draggable" >
<div class="draggable ui-widget-content card ui-draggable ui-draggable-handle" style="width:92%;max-width:300px;">

  <p>
    <strong>Name:</strong>
    <%= @card.name %>
  </p>

   <%= image_tag("img_avatar.png", alt:"Avatar", style:"width:100%") %>
  <div class="container">


<p>
  <strong>Description:</strong>
  <%= @card.description %>
</p>

<p>
  <strong>Height:</strong>
  <%= @card.height %>
</p>

<p>
  <strong>Birth:</strong>
  <%= @card.birth %>
</p>

<p>
  <strong>Jump:</strong>
  <%= @card.jump %>
</p>

<p>
  <strong>Trunfo:</strong>
  <%= @card.trunfo %>
</p>

<p>
  <strong>Imune:</strong>
  <%= @card.imune %>
</p>
  </div>
  <%= link_to 'Show', @card %>
  <%= link_to 'Edit', edit_card_path(@card) %>
  <%= link_to 'Destroy', @card, method: :delete, data: { confirm: 'Are you sure?' } %>

</div>
</div>
  <br>

trunfo/app/views/cards/_form.html.erb
<%= form_for(@card) do |f| %>
  <% if @card.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@card.errors.count, "error") %> prohibited this card from being saved:</h2>

      <ul>
      <% @card.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :height %><br>
    <%= f.number_field :height %>
  </div>
  <div class="field">
    <%= f.label :birth %><br>
    <%= f.date_select :birth %>
  </div>
  <div class="field">
    <%= f.label :jump %><br>
    <%= f.number_field :jump %>
  </div>
  <div class="field">
    <%= f.label :trunfo %><br>
    <%= f.check_box :trunfo %>
  </div>
  <div class="field">
    <%= f.label :imune %><br>
    <%= f.check_box :imune %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

trunfo/app/views/cards/_tablecards.html.erb
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Height</th>
      <th>Birth</th>
      <th>Jump</th>
      <th>Trunfo</th>
      <th>Imune</th>
      <th colspan="3"></th>
    </tr>
  </thead>
<%# TODO: write how to retrieve and display automatically card's attributes (key:value) card ex: card_attributes = {(name:name, description:description, etc:etc)} %>
  <tbody>
    <% @cards.each do |card| %>
      <tr>
        <td><%= card.name %></td>
        <td><%= card.description %></td>
        <td><%= card.height %></td>
        <td><%= card.birth %></td>
        <td><%= card.jump %></td>
        <td><%= card.trunfo %></td>
        <td><%= card.imune %></td>
        <td><%= link_to 'Show', card %></td>
        <td><%= link_to 'Edit', edit_card_path(card) %></td>
        <td><%= link_to 'Destroy', card, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

trunfo/app/views/cards/edit.html.erb
<h1>Editing Card</h1>

<%= render 'form' %>

<%= link_to 'Show', @card %> |
<%= link_to 'Back', cards_path %>

trunfo/app/views/cards/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Cards</h1>


<% @cards.each do |card| %>
<% @card = card %>
<%= render partial: 'card', locals: {card: @card} %>


<% end %>

<br>

<%= link_to 'New Card', new_card_path %>

trunfo/app/views/cards/new.html.erb
<h1>New Card</h1>

<%= render 'form' %>

<%= link_to 'Back', cards_path %>

trunfo/app/views/cards/show.html.erb
<p id="notice"><%= notice %></p>

<%= render partial: 'card' %>
<br>
Only to test: TODO remover!!
<ul id="sortable">
  <% 12.times do |i| %>
<li class="ui-state-default"><%= i + 1 %> </li>
 <% end %>
</ul>

<%= link_to 'Edit', edit_card_path(@card) %> |
<%= link_to 'Back', cards_path %>